# Generated by Django 5.2.7 on 2025-10-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date_reservation', models.DateField()),
                ('nombre_personnes', models.IntegerField()),
                ('commentaire', models.TextField(blank=True)),
            ],
        ),
    ]
