# Generated by Django 5.2.7 on 2025-11-02 19:04

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'ordering': ['-date_reservation', '-heure_reservation', '-created_at']},
        ),
        migrations.AddField(
            model_name='reservation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='heure_reservation',
            field=models.TimeField(default=datetime.time(19, 0)),
        ),
        migrations.AddField(
            model_name='reservation',
            name='telephone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date_reservation',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nom_client',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='nombre_personnes',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
