# Generated by Django 5.2.8 on 2025-12-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations_app', '0005_openinghour'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('label', models.CharField(blank=True, help_text='Ex : Jour férié, fermeture exceptionnelle, événement spécial…', max_length=100)),
                ('is_closed', models.BooleanField(default=False, help_text='Cochez si le salon est complètement fermé ce jour-là.')),
                ('heure_ouverture', models.TimeField(blank=True, help_text='Laisser vide si fermé toute la journée.', null=True)),
                ('heure_fermeture', models.TimeField(blank=True, help_text='Laisser vide si fermé toute la journée.', null=True)),
            ],
            options={
                'verbose_name': 'Jour spécial',
                'verbose_name_plural': 'Jours spéciaux',
                'ordering': ['date'],
            },
        ),
    ]
